import os
import json
import uuid
import time
from typing import Optional, Dict, Any, List
from backend.path_utils import get_cookies_dir

COOKIES_DIR = get_cookies_dir()

SUPPORTED_BROWSERS = [
    {"id": "chrome", "name": "Google Chrome", "icon": "chrome"},
    {"id": "edge", "name": "Microsoft Edge", "icon": "globe"},
    {"id": "firefox", "name": "Mozilla Firefox", "icon": "flame"},
    {"id": "brave", "name": "Brave Browser", "icon": "shield"},
    {"id": "opera", "name": "Opera", "icon": "circle-dot"},
    {"id": "vivaldi", "name": "Vivaldi", "icon": "compass"},
    {"id": "chromium", "name": "Chromium", "icon": "cpu"}
]

class CookieManager:
    def __init__(self):
        self.meta_file = os.path.join(COOKIES_DIR, "profiles.json")
        self._load_profiles()

    def _load_profiles(self):
        if os.path.exists(self.meta_file):
            try:
                with open(self.meta_file, "r", encoding="utf-8") as f:
                    self.profiles = json.load(f)
            except Exception:
                self.profiles = []
        else:
            self.profiles = []

    def _save_profiles(self):
        try:
            with open(self.meta_file, "w", encoding="utf-8") as f:
                json.dump(self.profiles, f, ensure_ascii=False, indent=2)
        except Exception as e:
            print(f"Error saving cookie profiles: {e}")

    def list_profiles(self) -> List[Dict[str, Any]]:
        self._load_profiles()
        # Проверяем реальное наличие файлов
        valid_profiles = []
        for p in self.profiles:
            file_path = os.path.join(COOKIES_DIR, p["filename"])
            if os.path.exists(file_path):
                p["size"] = os.path.getsize(file_path)
                valid_profiles.append(p)
        self.profiles = valid_profiles
        self._save_profiles()
        return self.profiles

    def save_cookie_text(self, name: str, content: str) -> Dict[str, Any]:
        """Сохраняет куки из строки (формат Netscape или обычный текст)"""
        profile_id = str(uuid.uuid4())[:8]
        clean_name = "".join(c for c in name if c.isalnum() or c in "._- ").strip() or "cookies"
        filename = f"{profile_id}_{clean_name}.txt"
        file_path = os.path.join(COOKIES_DIR, filename)

        # Добавляем стандартный заголовок Netscape, если отсутствует
        if not content.startswith("# Netscape HTTP Cookie File"):
            content = "# Netscape HTTP Cookie File\n# Generated by UniDownloader\n" + content

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

        profile = {
            "id": profile_id,
            "name": name,
            "filename": filename,
            "created_at": int(time.time()),
            "type": "file",
            "size": len(content)
        }
        self.profiles.append(profile)
        self._save_profiles()
        return profile

    def save_cookie_file(self, name: str, file_bytes: bytes) -> Dict[str, Any]:
        """Сохраняет загруженный файл cookies.txt"""
        profile_id = str(uuid.uuid4())[:8]
        clean_name = "".join(c for c in name if c.isalnum() or c in "._- ").strip() or "cookies.txt"
        filename = f"{profile_id}_{clean_name}"
        file_path = os.path.join(COOKIES_DIR, filename)

        with open(file_path, "wb") as f:
            f.write(file_bytes)

        profile = {
            "id": profile_id,
            "name": name,
            "filename": filename,
            "created_at": int(time.time()),
            "type": "file",
            "size": len(file_bytes)
        }
        self.profiles.append(profile)
        self._save_profiles()
        return profile

    def delete_profile(self, profile_id: str) -> bool:
        self._load_profiles()
        to_remove = None
        for p in self.profiles:
            if p["id"] == profile_id:
                to_remove = p
                break
        if to_remove:
            file_path = os.path.join(COOKIES_DIR, to_remove["filename"])
            if os.path.exists(file_path):
                try:
                    os.remove(file_path)
                except Exception:
                    pass
            self.profiles.remove(to_remove)
            self._save_profiles()
            return True
        return False

    def get_cookie_file_path(self, profile_id: str) -> Optional[str]:
        self._load_profiles()
        for p in self.profiles:
            if p["id"] == profile_id:
                file_path = os.path.join(COOKIES_DIR, p["filename"])
                if os.path.exists(file_path):
                    return file_path
        return None

    def get_supported_browsers(self) -> List[Dict[str, str]]:
        return SUPPORTED_BROWSERS

cookie_manager = CookieManager()
